### PR TITLE
Install and cache Rust

### PR DESCRIPTION
**Pull request by erikjohnston**
This should hopefully speed up installing Rust packages

### CODE REVIEW

**Comment by DMRobertson** [comment]
Not sure what this is trying to speed up. Do we often install rust packages from source rather than from wheels?

(I can see that this helps speed up installing Synapse, but I think we already include that Rust action wherever we want to install Synapse?)

**Comment by erikjohnston** [comment]
Alas, we don't always. Mainly due for linting in https://github.com/matrix-org/backend-meta/blob/release/v2/.github/workflows/python-poetry-ci.yml

Sorry, am trying to unpick the stack as I go here

**Comment by erikjohnston** [comment]
Yeah, maybe I should just add these steps to backend-meta

**Comment by DMRobertson** [comment]
> Yeah, maybe I should just add these steps to backend-meta

I think https://github.com/matrix-org/setup-python-poetry/issues/15 might be a better fit for that, tbh

**Pull request closed without merging**
